# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_bd/system_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd || ORIG_REF_NAME==system_bd} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_ps7_0_axi_periph_0/system_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_rst_ps7_0_50M_1/system_bd_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_processing_system7_0_2/system_bd_processing_system7_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_processing_system7_0_2 || ORIG_REF_NAME==system_bd_processing_system7_0_2} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_reram_axi_ip_0_7/system_bd_reram_axi_ip_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_reram_axi_ip_0_7 || ORIG_REF_NAME==system_bd_reram_axi_ip_0_7} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_bd_auto_pc_0 || ORIG_REF_NAME==system_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/system_bd/ip/system_bd_rst_ps7_0_50M_1/system_bd_rst_ps7_0_50M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system_bd/ip/system_bd_rst_ps7_0_50M_1/system_bd_rst_ps7_0_50M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system_bd/ip/system_bd_processing_system7_0_2/system_bd_processing_system7_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_processing_system7_0_2 || ORIG_REF_NAME==system_bd_processing_system7_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0_ooc.xdc

# XDC: bd/system_bd/system_bd_ooc.xdc
