# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/EightBitMemoryBlock/EightBitMemoryBlock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock || ORIG_REF_NAME==EightBitMemoryBlock} -quiet] -quiet

# IP: bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_processing_system7_0_0/EightBitMemoryBlock_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock_processing_system7_0_0 || ORIG_REF_NAME==EightBitMemoryBlock_processing_system7_0_0} -quiet] -quiet

# IP: bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_ps7_0_axi_periph_0/EightBitMemoryBlock_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock_ps7_0_axi_periph_0 || ORIG_REF_NAME==EightBitMemoryBlock_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock_rst_ps7_0_50M_0 || ORIG_REF_NAME==EightBitMemoryBlock_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_RegisterMemory_0_1/EightBitMemoryBlock_RegisterMemory_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock_RegisterMemory_0_1 || ORIG_REF_NAME==EightBitMemoryBlock_RegisterMemory_0_1} -quiet] -quiet

# IP: bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_auto_pc_0/EightBitMemoryBlock_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EightBitMemoryBlock_auto_pc_0 || ORIG_REF_NAME==EightBitMemoryBlock_auto_pc_0} -quiet] -quiet

# XDC: bd/EightBitMemoryBlock/EightBitMemoryBlock_ooc.xdc
