# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0.xci
# IP: The module: 'EightBitMemoryBlock_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0.xci
# IP: The module: 'EightBitMemoryBlock_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hrish/Downloads/ReRAM_Thesis/Project Folder/RegisterEightBitMemory/RegisterEightBitMemory.srcs/sources_1/bd/EightBitMemoryBlock/ip/EightBitMemoryBlock_rst_ps7_0_50M_0/EightBitMemoryBlock_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EightBitMemoryBlock_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
