# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ReRamSpm/ReRamSpm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm || ORIG_REF_NAME==ReRamSpm} -quiet] -quiet

# IP: bd/ReRamSpm/ip/ReRamSpm_processing_system7_0_0/ReRamSpm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm_processing_system7_0_0 || ORIG_REF_NAME==ReRamSpm_processing_system7_0_0} -quiet] -quiet

# IP: bd/ReRamSpm/ip/ReRamSpm_reram_axilite_wrapper_0_0/ReRamSpm_reram_axilite_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm_reram_axilite_wrapper_0_0 || ORIG_REF_NAME==ReRamSpm_reram_axilite_wrapper_0_0} -quiet] -quiet

# IP: bd/ReRamSpm/ip/ReRamSpm_ps7_0_axi_periph_0/ReRamSpm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm_ps7_0_axi_periph_0 || ORIG_REF_NAME==ReRamSpm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ReRamSpm/ip/ReRamSpm_rst_ps7_0_50M_0/ReRamSpm_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm_rst_ps7_0_50M_0 || ORIG_REF_NAME==ReRamSpm_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ReRamSpm/ip/ReRamSpm_auto_pc_0/ReRamSpm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ReRamSpm_auto_pc_0 || ORIG_REF_NAME==ReRamSpm_auto_pc_0} -quiet] -quiet

# XDC: bd/ReRamSpm/ip/ReRamSpm_processing_system7_0_0/ReRamSpm_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ReRamSpm_processing_system7_0_0 || ORIG_REF_NAME==ReRamSpm_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/ReRamSpm/ip/ReRamSpm_rst_ps7_0_50M_0/ReRamSpm_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ReRamSpm_rst_ps7_0_50M_0 || ORIG_REF_NAME==ReRamSpm_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ReRamSpm/ip/ReRamSpm_rst_ps7_0_50M_0/ReRamSpm_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ReRamSpm_rst_ps7_0_50M_0 || ORIG_REF_NAME==ReRamSpm_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/ReRamSpm/ip/ReRamSpm_auto_pc_0/ReRamSpm_auto_pc_0_ooc.xdc

# XDC: bd/ReRamSpm/ReRamSpm_ooc.xdc
