@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 12 12:26:51 +0200 2025
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_twin_range_sar_adc_behav -key {Behavioral:sim_1:Functional:tb_twin_range_sar_adc} -tclbatch tb_twin_range_sar_adc.tcl -view C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/ReRAM_On_FPGA/tb_twin_range_sar_adc_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
