# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/Zynq_book_tutorials/led_controller2/led_controller2.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xci
# IP: The module: 'led_test_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/Zynq_book_tutorials/led_controller2/led_controller2.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/Zynq_book_tutorials/led_controller2/led_controller2.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xci
# IP: The module: 'led_test_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/Zynq_book_tutorials/led_controller2/led_controller2.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_test_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
