# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RevisionDesign/RevisionDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign || ORIG_REF_NAME==RevisionDesign} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_processing_system7_0_0/RevisionDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_processing_system7_0_0 || ORIG_REF_NAME==RevisionDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_axi_reram_0_0/RevisionDesign_axi_reram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_axi_reram_0_0 || ORIG_REF_NAME==RevisionDesign_axi_reram_0_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_ps7_0_axi_periph_0/RevisionDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==RevisionDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_rst_ps7_0_50M_0/RevisionDesign_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==RevisionDesign_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_axi_bram_ctrl_0_0/RevisionDesign_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_axi_bram_ctrl_0_0 || ORIG_REF_NAME==RevisionDesign_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_blk_mem_gen_0_0/RevisionDesign_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_blk_mem_gen_0_0 || ORIG_REF_NAME==RevisionDesign_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_xbar_0/RevisionDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_xbar_0 || ORIG_REF_NAME==RevisionDesign_xbar_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_auto_pc_0/RevisionDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_auto_pc_0 || ORIG_REF_NAME==RevisionDesign_auto_pc_0} -quiet] -quiet

# IP: bd/RevisionDesign/ip/RevisionDesign_auto_pc_1/RevisionDesign_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RevisionDesign_auto_pc_1 || ORIG_REF_NAME==RevisionDesign_auto_pc_1} -quiet] -quiet

# XDC: bd/RevisionDesign/ip/RevisionDesign_processing_system7_0_0/RevisionDesign_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RevisionDesign_processing_system7_0_0 || ORIG_REF_NAME==RevisionDesign_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/RevisionDesign/ip/RevisionDesign_rst_ps7_0_50M_0/RevisionDesign_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RevisionDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==RevisionDesign_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/RevisionDesign/ip/RevisionDesign_rst_ps7_0_50M_0/RevisionDesign_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RevisionDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==RevisionDesign_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/RevisionDesign/ip/RevisionDesign_axi_bram_ctrl_0_0/RevisionDesign_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/RevisionDesign/ip/RevisionDesign_blk_mem_gen_0_0/RevisionDesign_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/RevisionDesign/ip/RevisionDesign_xbar_0/RevisionDesign_xbar_0_ooc.xdc

# XDC: bd/RevisionDesign/ip/RevisionDesign_auto_pc_0/RevisionDesign_auto_pc_0_ooc.xdc

# XDC: bd/RevisionDesign/ip/RevisionDesign_auto_pc_1/RevisionDesign_auto_pc_1_ooc.xdc

# XDC: bd/RevisionDesign/RevisionDesign_ooc.xdc
