# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DesignForPStoReg/DesignForPStoReg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg || ORIG_REF_NAME==DesignForPStoReg} -quiet] -quiet

# IP: bd/DesignForPStoReg/ip/DesignForPStoReg_processing_system7_0_0/DesignForPStoReg_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg_processing_system7_0_0 || ORIG_REF_NAME==DesignForPStoReg_processing_system7_0_0} -quiet] -quiet

# IP: bd/DesignForPStoReg/ip/DesignForPStoReg_simple_reg_0_0/DesignForPStoReg_simple_reg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg_simple_reg_0_0 || ORIG_REF_NAME==DesignForPStoReg_simple_reg_0_0} -quiet] -quiet

# IP: bd/DesignForPStoReg/ip/DesignForPStoReg_ps7_0_axi_periph_0/DesignForPStoReg_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg_ps7_0_axi_periph_0 || ORIG_REF_NAME==DesignForPStoReg_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DesignForPStoReg/ip/DesignForPStoReg_rst_ps7_0_50M_0/DesignForPStoReg_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg_rst_ps7_0_50M_0 || ORIG_REF_NAME==DesignForPStoReg_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DesignForPStoReg/ip/DesignForPStoReg_auto_pc_0/DesignForPStoReg_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DesignForPStoReg_auto_pc_0 || ORIG_REF_NAME==DesignForPStoReg_auto_pc_0} -quiet] -quiet

# XDC: bd/DesignForPStoReg/DesignForPStoReg_ooc.xdc
