webtalk_init -webtalk_dir C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/ReRAM_On_FPGA/ReRAM_On_FPGA.sim/sim_1/behav/xsim/xsim.dir/tb_twin_range_sar_adc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 12 12:33:31 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "903a0cffd6eb54f29cb3ba3878d501b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e9475fd1c9a64f4b944589391dd7ee2b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-1335U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2320 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8780_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3869084616 -regid "" -xml C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/ReRAM_On_FPGA/ReRAM_On_FPGA.sim/sim_1/behav/xsim/xsim.dir/tb_twin_range_sar_adc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/ReRAM_On_FPGA/ReRAM_On_FPGA.sim/sim_1/behav/xsim/xsim.dir/tb_twin_range_sar_adc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/ReRAM_On_FPGA/ReRAM_On_FPGA.sim/sim_1/behav/xsim/xsim.dir/tb_twin_range_sar_adc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
