set_property SRC_FILE_INFO {cfile:C:/Users/hrish/Downloads/Wahl_Thesis_Haris_Student_Arbeit/Zynq_book_tutorials/led_controller2/led_controller2.srcs/constrs_1/new/led_constraints.xdc rfile:../../../led_controller2.srcs/constrs_1/new/led_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14        [ get_ports {LEDs_out_0[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15        [ get_ports {LEDs_out_0[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14        [ get_ports {LEDs_out_0[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18        [ get_ports {LEDs_out_0[3]}]
